### ISSUE TITLE
Does not correctly handle immutable objects when hideRoot is false

### ISSUE THREAD

**Issue by leonaves** [alexkuz/react-json-tree#34]
Issue is here: https://github.com/chibicode/react-json-tree/blob/master/src/index.js#L81-L105

The getChildNodes function does not consider if the object of type immutable and breaks the detection in obj-type.js. An easy fix would be an `if objType(value) === 'Iterable'` somewhere in that function but I haven't submitted a PR because I have a feeling you'd want it done a bit more carefully.

**Comment by alexkuz** [comment]
I think this one is outdated, I just checked - `<JSONTree data={Immutable.map(data)}` hideRoot />` works fine, so I'm closing this.
