### ISSUE TITLE
Does not display well with custom line-height

### ISSUE THREAD

**Issue by bvaughn** [alexkuz/react-json-tree#41]
This is a minor nit but while working on an update to [bvaughn/redux-devtools-filterable-log-monitor](https://github.com/bvaughn/redux-devtools-filterable-log-monitor) I noticed that custom line-heights cause the JSON tree to display poorly.

#### Default browser line-height (eg. 20px)
<img width="216" alt="screen shot 2016-03-27 at 12 23 01 pm" src="https://cloud.githubusercontent.com/assets/29597/14067297/c24ab0e6-f416-11e5-8b7e-9f7f9689cca3.png">

#### Custom line-height (eg. 40px)
<img width="236" alt="screen shot 2016-03-27 at 12 23 10 pm" src="https://cloud.githubusercontent.com/assets/29597/14067299/cde2c84e-f416-11e5-95dd-0b7d87d6c146.png">

I think the "best" fix for this would be to use flexboxes to layout row items instead of using things like top margins for vertical alignment, etc. If you're interested- I'd be happy to put together a PR that addresses this. :)

**Comment by bvaughn** [comment]
Note that [flexbox support is quite good](http://caniuse.com/#feat=flexbox) so it seems like a safe change. Particularly given that this tool is for developers and so (in my experience) the partial IE support wouldn't really be a concern.

**Comment by alexkuz** [comment]
@bvaughn is this issue still relevant? Try this one:
```jsx
<JSONTree
    data={data}
    theme={{
      extend: theme,
      nestedNode: {
        lineHeight: '3em'
      },
      value:  {
        lineHeight: '3em'
      }
    }}
  />
```

**Comment by bvaughn** [comment]
Nice! Thanks for that tip Alex. I _think_ the last time I checked, the README only mentioned base16 theming. :)

This issue could be closed then I suppose, although I think switching to flex box would still be a positive change as it could render a lot of styling like the above unnecessary.

**Comment by alexkuz** [comment]
Yeah, I refactored styling recently.
I don't mind using flexbox, but I also don't want to waste the time on something that's not broken (at least for now) :) But if you believe it could be better - PR is always welcome.

**Comment by bvaughn** [comment]
Gotcha. Thanks for the refactor then. :)

Sure, sounds reasonable. I'll try to find some free time for it at some point!
