### ISSUE TITLE
value overflow

### ISSUE THREAD

**Issue by VinSpee** [alexkuz/react-json-tree#42]
Hi! I noticed a small bug when working on an API that returns a huge hash URL. The value overflows horizontally with scroll (expected behavior I presume, but maybe wrapping would be better? It would in this instance but maybe not always), but the background color does not grow with it.

![overflow](https://cloud.githubusercontent.com/assets/582828/12036511/a72465f2-ae14-11e5-9e27-20f32d533c1e.gif)

**Comment by alexkuz** [comment]
Fixed in `v0.7.2`
