### ISSUE TITLE
Support for immutable.js is broken

### ISSUE THREAD

**Issue by granmoe** [alexkuz/react-json-tree#45]
Per https://github.com/gaearon/redux-devtools/issues/265 react-json-tree seems to be causing immutable state trees to not display correctly in redux-devtools.

Using version 0.5.0 (known good version):

<img width="499" alt="screen shot 2016-04-14 at 2 11 46 pm" src="https://cloud.githubusercontent.com/assets/5620706/14540499/eea4e4a8-024a-11e6-8525-cfb6e09bd1a3.png">

Using version 0.6.5 (broken version):

<img width="497" alt="screen shot 2016-04-14 at 2 10 14 pm" src="https://cloud.githubusercontent.com/assets/5620706/14540517/0888515c-024b-11e6-987d-99878cf06e41.png">

I ran git bisect, starting with the two commits above, and it found the following result:

react-json-tree ((0f65000...)|BISECTING) $ git bisect bad
0f6500039aa93ebc742a2a58796ab37945724a23 is the first bad commit
commit 0f6500039aa93ebc742a2a58796ab37945724a23
Author: Kuzya <alexkuz@gmail.com>
Date:   Sat Feb 27 23:50:46 2016 +0300

    recursive collapsing for huge collections

:100644 100644 59bba58906c2502e8f582a7ac586a3831a65e6cb 9bf24bf8f54c432412c4cde6647d44bdbe3a8fc0 M	package.json
:040000 040000 5b97119e946ad7b78d148f7b1a1ae1308eb51adb c44859802f2a72a92f57fd1542fd76210e1cb9db M	src

**Comment by granmoe** [comment]
Here is a link to the breaking commit for convenience:

https://github.com/alexkuz/react-json-tree/commit/0f6500039aa93ebc742a2a58796ab37945724a23

**Comment by gaearon** [comment]
Thank you for inspecting this! Would you mind looking into possible fixes?

**Comment by granmoe** [comment]
I wish I could, but I won't have time to for a few months. I'm working full-time on a project with big deadlines coming up. We've decided to do without redux-devtools for now and just rely on a logger middleware.

**Comment by alexkuz** [comment]
@granmoe I published `v0.6.6` with a fix - can you check it out, please? (now any iterable object with defined `set()` method is treated as Map object)

**Comment by granmoe** [comment]
@alexkuz I don't see a v0.6.6 tag available. Can you point me to it? In the meantime, I'll just pull the latest from master and test with that.

**Comment by granmoe** [comment]
Disregard that, I found it on npm :-) I was only looking on here before, so I didn't see it. Testing in progress...

**Comment by granmoe** [comment]
Disregard that, I found it on npm :-) I was only looking on here before, so I didn't see it. Testing in progress...

**Comment by alexkuz** [comment]
Yeah, sorry, forgot to push it

**Comment by granmoe** [comment]
Tested via npm link trickery. Everything is working :-) Thanks. I created https://github.com/gaearon/redux-devtools-log-monitor/pull/52 to pull in the fix. After that one is accepted, we'll need a PR in redux-devtools to pull in the new version of redux-devtools-log-monitor.

**Comment by alexkuz** [comment]
Cool, I'm closing it then. Thank you for your help!
