### ISSUE TITLE
Theme not applied in v.0.10.0

### ISSUE THREAD

**Issue by foxhound87** [alexkuz/react-json-tree#56]
Theme styles (schemes and `isLightTheme`) not applied correctly in version `0.10.0`

All is working after downgrading to the version `0.9.0`

**Comment by aleury** [comment]
I came across this issue too. A property called [invertTheme](https://github.com/alexkuz/react-json-tree/blob/master/src/index.js#L77) is being defaulted to true and causing the unexpected theme behavior.

It looks like https://github.com/alexkuz/react-json-tree/pull/55 is an attempt to fix the docs.
