### ISSUE TITLE
Editable fields

### ISSUE THREAD

**Issue by sercanov** [alexkuz/react-json-tree#59]
Is there any plans on this ?

**Comment by alexkuz** [comment]
Not really. I think editable tree should be a separate module that could use this tree with customized renderers. We could add some hooks if needed but editability is out of scope for this project, I believe.

**Comment by zalmoxisus** [comment]
I'm also interested in this feature. If @sercanov wants to work on it, I'd help with hooks and integrations.

**Comment by sercanov** [comment]
Yeah sure, I'll try to find time to work on it. Eventually I'll need it soon.

**Comment by zalmoxisus** [comment]
@sercanov, I was thinking to add a context menu with an option `Edit`. When clicking on it, you get a modal with the selected object subtree inside, which you can edit as json. So, you can change not only the leaves, but also a subtree.

We have just to add to `react-json-tree` an optional right click event via props. Or even to integrate an optional context menu, as it could be useful for other cases, for example for copying to clipboard.

**Comment by Apercu** [comment]
Just for people that may be interested, I've added support for this feature in my own [fork](https://github.com/Apercu/react-json-tree-zavatta).

**Comment by yoiang** [comment]
@balthazar Installing via `yarn`/`npm` isn't working for me, it can't seem to find the module when I import by `react-json-tree` as well as `react-json-tree-zavatta`. I can give more insight but is there something I should be doing?
