### ISSUE TITLE
Override ItemRange Styling

### ISSUE THREAD

**Issue by rydash** [alexkuz/react-json-tree#67]
I have an Object containing 52 keys whose values are all different types.
When I render this object through to a JSONTree, I will see the following expandable element:
`>> 46...48`

I want to force that object to always be expanded, regardless of how large the overall object ends up being. And in this example, we're only hiding 3 small entries...which seems silly. By the way, the `showObjectKeys` key does not enforce the behavior I'm looking for.

If there's a way to accomplish this with the styling options, I absolutely cannot find it. I'd love any help or insight here!

**Comment by alexkuz** [comment]
You can use `collectionLimit` for that (default is `50`). Which should be in README, indeed.

Also, there is no `showObjectKeys` prop, only `sortObjectKeys`.

**Comment by rydash** [comment]
Ahh, this is perfect!

(And I'm an ignorant boob - the key I meant to mention was `shouldExpandNode`,  but then I guess I just made one up. Sorry about that!)

**Comment by rydash** [comment]
Ahh, this is perfect!

(And I'm an ignorant boob - the key I meant to mention was `shouldExpandNode`,  but then I guess I just made one up. Sorry about that!)
