### ISSUE TITLE
CSS Styling Help

### ISSUE THREAD

**Issue by edgeadjei** [alexkuz/react-json-tree#73]
I'm trying to style my component using a className but I'm having no success.
The theme section of the README is a little confusing and doesn't specify the target HTML tags or classes for styling.

I would like to represent the sample below using CSS
```js
<JsonTree 
 data={data} 
 hideRoot={true} 
 theme={{base00: '#000', base0B: brand.primaryColor, base0D: '#999'}} />
```

**Comment by alexkuz** [comment]
The component uses inline styles by default, so yeah, using classnames is a bit tricky.

You can do it like this:
```js
theme={{
  tree: () => ({ className: 'myTreeClassName' }), // we use function here to override default styles, leaving only custom class
  label: () => ({ className: 'myTreeLabelClassName' }),
  ...
}}
```
but you'll have to copy all corresponding styles to you classes
(you can find all available keys and default styles here: https://github.com/alexkuz/react-json-tree/blob/master/src/createStylingFromTheme.js#L35)

The original idea for styling is described [here](https://github.com/markdalgleish/react-themeable), it's maybe easier to understand.

The difference here is that in addition to string (classname) or object (style), that would be merged with defaults, you can provide a function, that returns object `{ className, style }`, like we did above, so the defaults could be completely overwritten.

If you just want to replace colors with ones in your CSS and don't want to copy-paste other styles in your CSS, you can do it in a more fine-tuned way:

```js
theme={{
  tree: ({ style }) => ({
    style: { ...style, backgroundColor: undefined }, // removing default background color from styles
    className:  'myTreeClassName'
  }),
  ...
}}
```
Sorry for confusion :)

**Comment by edgeadjei** [comment]
Thank you for the quick reply this is exactly what I'm looking for. Everything works as expected but I'm having trouble updating the arrowSign font color. it looks like the returned style doesn't contain the default styles.  

```js
arrowSign: ({style}) => {
  console.log(style);  // Object {color: "#2287cd"}
   style: Object.assign({}, style, {color: "red"})
},
```

**Comment by alexkuz** [comment]
Yes, it looks like a bug, thank you.

But for arrowSign you can just use a plain object - I checked, it works fine:
```js
arrowSign: { color: 'red' }
```

**Comment by edgeadjei** [comment]
Perfect thank you.

**Comment by alexkuz** [comment]
The latest version has a fix for that - overriding arrowSign should work now with any solution.
