### ISSUE TITLE
Use of React 15.1.0 breaks redux-devtools-inspector

### ISSUE THREAD

**Issue by callumsong** [alexkuz/react-json-tree#74]
Thanks so much for the updates and upgrades first of all!

I am using 15.1.0 as part of my production build (it's sadly fixed and we can't upgrade to a newer version) and we also use version 0.9.4 of redux-devtools-inspector. This has a dependency of `^0.10.0` on `react-json-tree` (which has been recently updated to `0.10.6`), which in turn has updated the peerDependencies to `15.3.0` (which we sadly can't update to :cry:).

Is it possible to have this version as `0.11.0`, or a way that we don't have to upgrade our React version at all?

**Comment by alexkuz** [comment]
You're right, I shouldn't have upgraded react without updating minor version at least.

**Comment by alexkuz** [comment]
Try `v0.10.7` now, I downgraded react dependency to `15.0.0`.
The future versions of `react-json-tree`, starting from `1.0.0`, will use `15.3.0`.

**Comment by callumsong** [comment]
Totally forgot to say I tried it and it's now fine - thanks!
