### ISSUE TITLE
Version 0.10.8 ships unnecessary artifacts

### ISSUE THREAD

**Issue by lgeiger** [alexkuz/react-json-tree#79]
Hi @alexkuz,

it looks like something went wrong during the last release. The release on `npm` includes a `packages/react-json-tree-demo-app` folder of 71 MB.

This makes our build fail due to `flow` errors: https://travis-ci.org/nteract/hydrogen#L178

**Comment by alexkuz** [comment]
Ouch.

**Comment by alexkuz** [comment]
Fixed, thank you!

**Comment by lgeiger** [comment]
Awesome thanks.
