### ISSUE TITLE
sortObjectKeys={true} can't be used on firefox

### ISSUE THREAD

**Issue by iascchen** [alexkuz/react-json-tree#83]
sortObjectKeys={true} can't be used on firefox, firefox version is 53.0.3 (64 bit) of OSX.
It is working on chrome.

**Comment by jayphelps** [comment]
It doesn't work for me either, even in Chrome.

Taking a look at the source, I can't find any place that the boolean variant would be correctly handled. Perhaps the docs are just out of date and it only supports the function now? If the maintainers confirm, I'm happy to update them.

https://github.com/alexkuz/react-json-tree/blob/7afcfae54d8b5e1ce6db607ec75e12eb188274a7/src/getCollectionEntries.js#L21-L23

**Comment by retrofox** [comment]
>  Perhaps the docs are just out of date and it only supports the function now?

That seems to be true. Getting the same issue here.

> arr.sort([compareFunction])
> Parameters
> compareFunction: Optional
> 
> Specifies a function that defines the sort order. If omitted, the array is sorted according to each character's Unicode code point value, according to the string conversion of each element.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by nhunzaker** [comment]
I just hit this too. I'll send out a PR.
